### ISSUE TITLE
The composer install hangs

### ISSUE THREAD

**Issue by frob** [blastehh/pterodactyl_ansible#6]
I had to modify the composer install with `become_user: ubuntu` to get it to work. This is likely a new change in composer where it prompts you if you attempt to run `composer install` as root. 

I would put forward a PR but my fix doesn't support centOS or debian. Maybe add an app user `pterodactyl` or something and use that user?

**Comment by blastehh** [comment]
Just curious because I don't get these errors myself:
Does ansible log in to your server with the root user? What about if ansible logs in directly as your ubuntu user?

The upgrade playbook also runs a composer install, so if that also errors for you without a different become_user, that could be something to check.

**Comment by Freebase394** [comment]
Hi guys! 
Any update on this ?
I will try, and i will coment it soon ...  🙂
